name: CI

on:
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:    
      - uses: actions/checkout@v2

      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64

      - name: Install Dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements-dev.txt 

      - name: Run Tests        
        run: pytest whotofollow_api

      - name: Run Black
        run: black whotofollow_api --check
